spring:
  profiles: prod

  ## mysql
my:
  dynamic:
    datasource:
      enable: true
      defaultDatasourceName: master
      datasourceList:
        - name: master
          url: jdbc:mysql://40.73.77.122:3306/smart_home?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=CTT
          username: root
          password: aA123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          maxActive: 50
          initialSize: 5
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          minEvictableIdleTimeMillis: 300000
        #       maxWait: 60000
        #       minIdle: 1
        #       timeBetweenEvictionRunsMillis: 60000

        #       spring.datasource.filters: stat
        - name: slave
          url: jdbc:mysql://47.103.49.45:3306/smart_home?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=CTT
          username: root
          password: aA123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          maxActive: 50
          initialSize: 5
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          minEvictableIdleTimeMillis: 300000


 #配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


