spring:
  profiles: prod
  mail:
    host: smtp.163.com
    port: 25
    username: shizg666@163.com
    password: shizg666
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.16.0.85:8848
#  data:
#    mongodb:
#      uri: mongodb://root:aA123456@172.16.0.85:27017,172.16.0.86:27017,172.16.0.87:27017/cloud?authSource=cloud&replicaSet=cloud&slaveOk=true&write=1&readPreference=secondaryPreferred
#      connections-per-host: 50
#      #每个实例允许链接的最大数
#      threads-allowed-to-block-for-connection-multiplier: 50
#      # 超时时间
#      connect-timeout: 5000
#      socket-timeout: 3000
#      max-wait-time: 1500
#      #控制是否在一个连接时，系统会自动重试
#      auto-connect-retry: true
#      socket-keep-alive: true
  ## mysql
#  datasource:
#    url: jdbc:mysql://49.232.174.101:3306/smart_home?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=CTT
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 1
#    minIdle: 3
#    maxActive: 100
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
  ## redis链接
  redis:
    database: 0
## 如果是单点的redis，打开以下配置 start
    host: 49.232.174.101
    port: 6379
## 单点redis配置结束 end
    password: shi123456
## 如果是sentinel，打开以下配置 start
#    sentinel:
#      master: mymaster
#      nodes: [172.16.0.85:26379,172.16.0.86:26379,172.16.0.87:26379]
## sentinel配置结束
    lettuce:
      pool:
         # 连接池中的最大空闲连接 默认8      
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
    timeout: 30000ms

# 配置slq打印日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



ditu:
  ak: dvBKa0Y3dcz7oZG3RgCXU3TN1gGMFQUF
web:
  app-pic-path: http://www.lokosmart.com:9000/images/appicon/

#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 10000
#        read-timeout: 30000
#      smarthome-mc:
#        connect-timeout: 10000
#        read-timeout: 30000
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 5000
#  MaxAutoRetries: 3
#  OkToRetryOnAllOperations: false
